api = "0.10"

[extension]
id = "wilsonrf/com.wilsonfranca.aws-lambda-rie-extension"
version = "0.0.2"
name = "AWS RIE Extension"
homepage = "https://github.com/wilsonrf/aws-lambda-rie-extension"
description = "A simple extension that installs aws lambda runtime interface emulator to the run image"

[metadata]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  include-files = ["linux/amd64/bin/generate",
    "linux/amd64/bin/detect",
    "linux/amd64/bin/run",
    "linux/arm64/bin/generate",
    "linux/arm64/bin/detect",
    "linux/arm64/bin/run",
    "extension.toml"]

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"