# Buildpack API version
api = "0.10"

# Extension ID and metadata
[extension]
id = "wilsonrf/com.wilsonfranca.aws-lambda-rie-extension"
version = "0.0.1"
name = "AWS RIE Extension"
homepage = "https://github.com/wilsonrf/aws-lambda-rie-extension"
description = "A simple extension that installs aws lambda runtime interface emulator to the run image"

[metadata]
  pre-package = "./scripts/build.sh"
  include-files = ["bin/generate", "bin/detect", "bin/run", "extension.toml"]